var MSG = {
  title: "Koda",
  blocks: "Delčki",
  linkTooltip: "Shrani in poveži z delčki.",
  runTooltip: "Poženi program, določen z delčki v delovnem prostoru.",
  badCode: "Napaka programa:\n%1",
  timeout: "Preseženo največje število iteracij izvajanja.",
  trashTooltip: "Odstrani vse delčke.",
  catLogic: "Pogoji",
  catLoops: "Zanke",
  catMath: "Matematika",
  catText: "Besedilo",
  catLists: "Tabele",
  catColour: "Barve",
  catVariables: "Spremenljivke",
  catFunctions: "Funkcije",
  catTurtle: "Želva",
  listVariable: "tabela",
  textVariable: "besedilo",
  httpRequestError: "Pojavila se je težava z zahtevo.",
  linkAlert: "Deli svoje delčke s povezavo:\n\n%1",
  hashError: "Oprosti, '%1' ne ustreza nobenemu shranjenemu programu.",
  xmlError: "Ne morem naložiti datoteke. Morda je bila ustvarjena z drugo različico programa Blockly?",
  badXml: "Napaka pri razčlenjevanju XML:\n%1\n\nKlikni 'V redu' in opusti spremembe ali 'Prekliči' za nadaljevanje urejanja XML."
};
