var MSG = {
  title: "Koda",
  blocks: "Kocke",
  linkTooltip: "Shrani in poveži s kockami.",
  runTooltip: "Poženi program, določen s kockami v delovnem prostoru.",
  badCode: "Napaka programa:\n%1",
  timeout: "Preseženo največje število iteracij izvajanja.",
  trashTooltip: "Odstrani vse kocke.",
  catLogic: "Pogoji",
  catLoops: "Zanke",
  catMath: "Matematika",
  catText: "Besedilo",
  catLists: "Tabele",
  catColour: "Barve",
  catVariables: "Spremenljivke",
  catFunctions: "Funkcije",
  catTurtle: "Želva",
  listVariable: "tabela",
  textVariable: "besedilo",
  httpRequestError: "Pojavila se je težava z zahtevo.",
  linkAlert: "Delite svoje kocke s povezavo:\n\n%1",
  hashError: "Oprostite, '%1' ne ustreza nobenemu shranjenemu programu.",
  xmlError: "Ne morem naložiti datoteke. Morda je bila ustvarjena z drugo različico programa Blockly?",
  badXml: "Napaka pri razčlenjevanju XML:\n%1\n\nKliknite 'OK' in opustite spremembe ali 'Prekliči' za nadaljevanje urejanja XML."
};
